version: 2
sources:
  - name: stripe
    database: raw

    loaded_at_field: created::timestamp
    
    freshness:
      warn_after: {count: 1, period: day}
      error_after: {count: 2, period: day}      
  
    tables:
      - name: payment
        columns:
          - name: "ID"
            tests:
              - unique
              - not_null

  - name: jaffle_shop
    database: raw  
  
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orders
        columns: 
          - name: id
            tests:
              - unique
              - not_null
        loaded_at_field: order_date::timestamp 
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}                   

models:
  - name: dim_customers
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id            
  - name: fact_orders
    description: "{{ doc('fact_orders') }}"

    columns:
      - name: order_id
        description: "{{ doc('order_id') }}"

        tests:
          - not_null 
          - relationships:
              to: ref('stg_orders')
              field: order_id            
      - name: customer_id
        description: foreign key to dim_customers
        tests:
          - not_null  
          - relationships:
              to: ref('dim_customers')
              field: customer_id 
      - name: paymentmethod
        description: payment method used (provided by stripe)
        tests:
          - not_null
          - accepted_values:
              values: ['credit_card','coupon','bank_transfer','gift_card']                                         
  - name: stg_customers
    description: Model cleans up customer data
    columns:
      - name: customer_id
        description: Customer ID
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: Model cleans up orders
    columns:
      - name: order_id
        description: Order ID
        tests:
          - unique
          - not_null
      - name: status
        description: Denotes order status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        description: Foreign key to Customers table
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id